service: scene-finder

provider:
  name: aws
  runtime: nodejs8.10
  profile: scene-finder  # Default: default
  region: ${opt:region, 'ap-northeast-1'}  # Default: us-east-1
  stage: ${opt:region, 'beta'}  # Default: dev

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: 'api-${self:provider.stage}.yokrh.com'
    certificateName: '*.yokrh.com'
    stage: ${self:provider.stage}
    basePath: 'scene-finder'
    createRoute53Record: false  # Default: true.
    #Creating a new Route53 record in other account is not supported.
    #Should add A record with alias manually from https://console.aws.amazon.com/route53/home#hosted-zones:
    #Issue: https://github.com/amplify-education/serverless-domain-manager/issues/233

functions:
  fc-index:
    handler: index.handler
    events:  # should be same as express router
      - http:
          method: options
          path: /{any+}  # wildcard
      - http:
          method: get
          path: /health
      - http:
          method: get
          path: /store/{proxy+}  # for /ytdl/download. Only 1 depth is allowed.
